%YAML:1.0
#common parameters
imu_topic: "/mynteye/imu/data_raw"
image_topic: "/mynteye/left/image_mono"
output_path: "/dev/null"

use_mynteye_adapter: 1
# mynteye_imu_srv: "d"

model_type: PINHOLE
camera_name: pinhole
image_width: 640
image_height: 480
distortion_parameters:
   k1: 2.2106170654296875e-02
   k2: 3.4332275390625000e-03
   p1: -5.8364868164062500e-04
   p2: -1.5220642089843750e-03
projection_parameters:
   fx: 5.2193524169921875e+02
   fy: 5.2176794433593750e+02
   cx: 3.0151367187500000e+02
   cy: 2.3699928283691406e+02

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam

extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9996651999999997e-01, 4.3087300000000002e-03,
       6.9571800000000003e-03, 4.3487800000000000e-03,
       -9.9997400999999997e-01, -5.7512800000000001e-03,
       6.9322200000000002e-03, 5.7813500000000002e-03,
       -9.9995926000000002e-01 ]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -4.7773620000000003e-02, -2.2373099999999997e-03,
       -1.6007100000000000e-03 ]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 10            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.00253          # accelerometer measurement noise standard deviation. #0.599298904976
#acc_n: 0.02024
gyr_n: 0.0291        # gyroscope measurement noise standard deviation.     #0.198614898699
#gyr_n: 0.2328
acc_w: 2.04543326912e-05         # accelerometer bias random work noise standard deviation.  #0.02
#acc_w: 1.636347e-04
gyr_w: 0.00088056       # gyroscope bias random work noise standard deviation.     #4.0e-5
#gyr_w: 0.00704448

#imu parameters       The more accurate parameters you provide, the better performance
#acc_n: 7.6509e-02           # accelerometer measurement noise standard deviation. #0.599298904976
#gyr_n: 9.0086e-03          # gyroscope measurement noise standard deviation.     #0.198614898699
#acc_w: 5.3271e-02        # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 5.5379e-05        # gyroscope bias random work noise standard deviation.     #4.0e-5

g_norm: 9.806    # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/you/local/path/to/mynteye/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0                       # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
